### ISSUE TITLE
Streams double-post when defined as a global plugin *and* a channel plugin

### ISSUE THREAD

**Issue by x89** [anlutro/botologist#74]
If you have the following in your config for example:
```yaml
…
global_plugins:
  - streams

channels:
  - channel: '##channel'
    plugins:
      - streams
…
```

Then the stream will be echoed twice in `##channel` every tick.
